# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _iric
else:
    import _iric

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class IntArrayContainer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, size):
        _iric.IntArrayContainer_swiginit(self, _iric.new_IntArrayContainer(size))
    __swig_destroy__ = _iric.delete_IntArrayContainer

    def size(self):
        return _iric.IntArrayContainer_size(self)

    def value(self, index):
        return _iric.IntArrayContainer_value(self, index)

    def setValue(self, index, v):
        return _iric.IntArrayContainer_setValue(self, index, v)

    def pointer(self):
        return _iric.IntArrayContainer_pointer(self)

# Register IntArrayContainer in _iric:
_iric.IntArrayContainer_swigregister(IntArrayContainer)

class RealArrayContainer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, size):
        _iric.RealArrayContainer_swiginit(self, _iric.new_RealArrayContainer(size))
    __swig_destroy__ = _iric.delete_RealArrayContainer

    def size(self):
        return _iric.RealArrayContainer_size(self)

    def value(self, index):
        return _iric.RealArrayContainer_value(self, index)

    def setValue(self, index, v):
        return _iric.RealArrayContainer_setValue(self, index, v)

    def pointer(self):
        return _iric.RealArrayContainer_pointer(self)

# Register RealArrayContainer in _iric:
_iric.RealArrayContainer_swigregister(RealArrayContainer)


def cg_iRIC_Read_BC_Count_WithGridId(fid, gid, type):
    return _iric.cg_iRIC_Read_BC_Count_WithGridId(fid, gid, type)

def cg_iRIC_Read_BC_IndicesSize_WithGridId(fid, gid, type, num):
    return _iric.cg_iRIC_Read_BC_IndicesSize_WithGridId(fid, gid, type, num)

def cg_iRIC_Read_BC_IndicesSize2_WithGridId(fid, gid, type, num):
    return _iric.cg_iRIC_Read_BC_IndicesSize2_WithGridId(fid, gid, type, num)

def cg_iRIC_Read_BC_Integer_WithGridId(fid, gid, type, num, name):
    return _iric.cg_iRIC_Read_BC_Integer_WithGridId(fid, gid, type, num, name)

def cg_iRIC_Read_BC_Real_WithGridId(fid, gid, type, num, name):
    return _iric.cg_iRIC_Read_BC_Real_WithGridId(fid, gid, type, num, name)

def cg_iRIC_Read_BC_String_WithGridId(fid, gid, type, num, name):
    return _iric.cg_iRIC_Read_BC_String_WithGridId(fid, gid, type, num, name)

def cg_iRIC_Read_BC_FunctionalSize_WithGridId(fid, gid, type, num, name):
    return _iric.cg_iRIC_Read_BC_FunctionalSize_WithGridId(fid, gid, type, num, name)

def cg_iRIC_Read_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname):
    return _iric.cg_iRIC_Read_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname)

def cg_iRIC_Clear_BC_WithGridId(fid, gid):
    return _iric.cg_iRIC_Clear_BC_WithGridId(fid, gid)

def cg_iRIC_Write_BC_Integer_WithGridId(fid, gid, type, num, name, value):
    return _iric.cg_iRIC_Write_BC_Integer_WithGridId(fid, gid, type, num, name, value)

def cg_iRIC_Write_BC_Real_WithGridId(fid, gid, type, num, name, value):
    return _iric.cg_iRIC_Write_BC_Real_WithGridId(fid, gid, type, num, name, value)

def cg_iRIC_Write_BC_String_WithGridId(fid, gid, type, num, name, value):
    return _iric.cg_iRIC_Write_BC_String_WithGridId(fid, gid, type, num, name, value)

def cg_iRIC_Write_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname, value):
    return _iric.cg_iRIC_Write_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname, value)

def cg_iRIC_Read_Integer(fid, name):
    return _iric.cg_iRIC_Read_Integer(fid, name)

def cg_iRIC_Read_Real(fid, name):
    return _iric.cg_iRIC_Read_Real(fid, name)

def cg_iRIC_Read_String(fid, name):
    return _iric.cg_iRIC_Read_String(fid, name)

def cg_iRIC_Read_FunctionalSize(fid, name):
    return _iric.cg_iRIC_Read_FunctionalSize(fid, name)

def cg_iRIC_Read_FunctionalWithName_String(fid, name, paramname):
    return _iric.cg_iRIC_Read_FunctionalWithName_String(fid, name, paramname)

def cg_iRIC_Write_Integer(fid, name, value):
    return _iric.cg_iRIC_Write_Integer(fid, name, value)

def cg_iRIC_Write_Real(fid, name, value):
    return _iric.cg_iRIC_Write_Real(fid, name, value)

def cg_iRIC_Write_String(fid, name, value):
    return _iric.cg_iRIC_Write_String(fid, name, value)

def cg_iRIC_Write_FunctionalWithName_String(fid, name, paramname, value):
    return _iric.cg_iRIC_Write_FunctionalWithName_String(fid, name, paramname, value)

def cg_iRIC_Read_Complex_Count_WithBaseId(fid, bid, groupname):
    return _iric.cg_iRIC_Read_Complex_Count_WithBaseId(fid, bid, groupname)

def cg_iRIC_Read_Complex_Integer_WithBaseId(fid, bid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_Integer_WithBaseId(fid, bid, groupname, num, name)

def cg_iRIC_Read_Complex_Real_WithBaseId(fid, bid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_Real_WithBaseId(fid, bid, groupname, num, name)

def cg_iRIC_Read_Complex_String_WithBaseId(fid, bid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_String_WithBaseId(fid, bid, groupname, num, name)

def cg_iRIC_Read_Complex_FunctionalSize_WithBaseId(fid, bid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_FunctionalSize_WithBaseId(fid, bid, groupname, num, name)

def cg_iRIC_Read_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname):
    return _iric.cg_iRIC_Read_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname)

def cg_iRIC_Clear_Complex_WithBaseId(fid, bid):
    return _iric.cg_iRIC_Clear_Complex_WithBaseId(fid, bid)

def cg_iRIC_Write_Complex_Integer_WithBaseId(fid, bid, groupname, num, name, value):
    return _iric.cg_iRIC_Write_Complex_Integer_WithBaseId(fid, bid, groupname, num, name, value)

def cg_iRIC_Write_Complex_Real_WithBaseId(fid, bid, groupname, num, name, value):
    return _iric.cg_iRIC_Write_Complex_Real_WithBaseId(fid, bid, groupname, num, name, value)

def cg_iRIC_Write_Complex_String_WithBaseId(fid, bid, groupname, num, name, value):
    return _iric.cg_iRIC_Write_Complex_String_WithBaseId(fid, bid, groupname, num, name, value)

def cg_iRIC_Write_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname, value):
    return _iric.cg_iRIC_Write_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname, value)

def iRIC_Geo_Polygon_Open(filename):
    return _iric.iRIC_Geo_Polygon_Open(filename)

def iRIC_Geo_Polygon_Read_IntegerValue(id):
    return _iric.iRIC_Geo_Polygon_Read_IntegerValue(id)

def iRIC_Geo_Polygon_Read_RealValue(id):
    return _iric.iRIC_Geo_Polygon_Read_RealValue(id)

def iRIC_Geo_Polygon_Read_PointCount(id):
    return _iric.iRIC_Geo_Polygon_Read_PointCount(id)

def iRIC_Geo_Polygon_Read_HoleCount(id):
    return _iric.iRIC_Geo_Polygon_Read_HoleCount(id)

def iRIC_Geo_Polygon_Read_HolePointCount(id, holeid):
    return _iric.iRIC_Geo_Polygon_Read_HolePointCount(id, holeid)

def iRIC_Geo_Polygon_Close(id):
    return _iric.iRIC_Geo_Polygon_Close(id)

def iRIC_Geo_RiverSurvey_Open(filename):
    return _iric.iRIC_Geo_RiverSurvey_Open(filename)

def iRIC_Geo_RiverSurvey_Read_Count(id):
    return _iric.iRIC_Geo_RiverSurvey_Read_Count(id)

def iRIC_Geo_RiverSurvey_Read_Position(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_Position(id, pointid)

def iRIC_Geo_RiverSurvey_Read_Direction(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_Direction(id, pointid)

def iRIC_Geo_RiverSurvey_Read_Name(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_Name(id, pointid)

def iRIC_Geo_RiverSurvey_Read_RealName(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_RealName(id, pointid)

def iRIC_Geo_RiverSurvey_Read_LeftShift(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_LeftShift(id, pointid)

def iRIC_Geo_RiverSurvey_Read_AltitudeCount(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_AltitudeCount(id, pointid)

def iRIC_Geo_RiverSurvey_Read_FixedPointL(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_FixedPointL(id, pointid)

def iRIC_Geo_RiverSurvey_Read_FixedPointR(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_FixedPointR(id, pointid)

def iRIC_Geo_RiverSurvey_Read_WaterSurfaceElevation(id, pointid):
    return _iric.iRIC_Geo_RiverSurvey_Read_WaterSurfaceElevation(id, pointid)

def iRIC_Geo_RiverSurvey_Close(id):
    return _iric.iRIC_Geo_RiverSurvey_Close(id)

def cg_iRIC_Read_Geo_Count(fid, name):
    return _iric.cg_iRIC_Read_Geo_Count(fid, name)

def cg_iRIC_Read_Geo_Filename(fid, name, geoid):
    return _iric.cg_iRIC_Read_Geo_Filename(fid, name, geoid)

def cg_iRIC_Read_Grid2d_Str_Size_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid2d_Str_Size_WithGridId(fid, gid)

def cg_iRIC_Read_Grid3d_Str_Size_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid3d_Str_Size_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_TriangleElementsSize_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_TriangleElementsSize_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_TriangleElementsSize2_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_TriangleElementsSize2_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_IFaceCount_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_IFaceCount_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_JFaceCount_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_JFaceCount_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_KFaceCount_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid_KFaceCount_WithGridId(fid, gid)

def cg_iRIC_Read_Grid_FunctionalDimensionSize_WithGridId(fid, gid, name, dimname):
    return _iric.cg_iRIC_Read_Grid_FunctionalDimensionSize_WithGridId(fid, gid, name, dimname)

def cg_iRIC_Read_Grid_FunctionalTimeSize_WithGridId(fid, gid, name):
    return _iric.cg_iRIC_Read_Grid_FunctionalTimeSize_WithGridId(fid, gid, name)

def cg_iRIC_Read_Grid2d_Open_WithGridId(fid, gid):
    return _iric.cg_iRIC_Read_Grid2d_Open_WithGridId(fid, gid)

def cg_iRIC_Read_Sol_Grid2d_Open_WithGridId(fid, gid, solid):
    return _iric.cg_iRIC_Read_Sol_Grid2d_Open_WithGridId(fid, gid, solid)

def cg_iRIC_Read_Grid2d_Close(grid_handle):
    return _iric.cg_iRIC_Read_Grid2d_Close(grid_handle)

def cg_iRIC_Read_Grid2d_CellArea(grid_handle, cellId):
    return _iric.cg_iRIC_Read_Grid2d_CellArea(grid_handle, cellId)

def cg_iRIC_Read_Grid2d_FindCell(grid_handle, x, y):
    return _iric.cg_iRIC_Read_Grid2d_FindCell(grid_handle, x, y)

def cg_iRIC_Read_Grid2d_CellNodeCount(grid_handle, cellId):
    return _iric.cg_iRIC_Read_Grid2d_CellNodeCount(grid_handle, cellId)

def iRIC_Check_Cancel():
    return _iric.iRIC_Check_Cancel()

def cg_iRIC_Open(filename, mode):
    return _iric.cg_iRIC_Open(filename, mode)

def cg_iRIC_Close(fid):
    return _iric.cg_iRIC_Close(fid)

def iRIC_InitOption(option):
    return _iric.iRIC_InitOption(option)

def cg_iRIC_Read_Complex_Count(fid, groupname):
    return _iric.cg_iRIC_Read_Complex_Count(fid, groupname)

def cg_iRIC_Read_Complex_Integer(fid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_Integer(fid, groupname, num, name)

def cg_iRIC_Read_Complex_Real(fid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_Real(fid, groupname, num, name)

def cg_iRIC_Read_Complex_String(fid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_String(fid, groupname, num, name)

def cg_iRIC_Read_Complex_FunctionalSize(fid, groupname, num, name):
    return _iric.cg_iRIC_Read_Complex_FunctionalSize(fid, groupname, num, name)

def cg_iRIC_Read_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname):
    return _iric.cg_iRIC_Read_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname)

def cg_iRIC_Clear_Complex(fid):
    return _iric.cg_iRIC_Clear_Complex(fid)

def cg_iRIC_Write_Complex_Integer(fid, groupname, num, name, value):
    return _iric.cg_iRIC_Write_Complex_Integer(fid, groupname, num, name, value)

def cg_iRIC_Write_Complex_Real(fid, groupname, num, name, value):
    return _iric.cg_iRIC_Write_Complex_Real(fid, groupname, num, name, value)

def cg_iRIC_Write_Complex_String(fid, groupname, num, name, value):
    return _iric.cg_iRIC_Write_Complex_String(fid, groupname, num, name, value)

def cg_iRIC_Write_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname, value):
    return _iric.cg_iRIC_Write_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname, value)

def cg_iRIC_Read_BC_Count(fid, type):
    return _iric.cg_iRIC_Read_BC_Count(fid, type)

def cg_iRIC_Read_BC_IndicesSize(fid, type, num):
    return _iric.cg_iRIC_Read_BC_IndicesSize(fid, type, num)

def cg_iRIC_Read_BC_IndicesSize2(fid, type, num):
    return _iric.cg_iRIC_Read_BC_IndicesSize2(fid, type, num)

def cg_iRIC_Read_BC_Integer(fid, type, num, name):
    return _iric.cg_iRIC_Read_BC_Integer(fid, type, num, name)

def cg_iRIC_Read_BC_Real(fid, type, num, name):
    return _iric.cg_iRIC_Read_BC_Real(fid, type, num, name)

def cg_iRIC_Read_BC_String(fid, type, num, name):
    return _iric.cg_iRIC_Read_BC_String(fid, type, num, name)

def cg_iRIC_Read_BC_FunctionalSize(fid, type, num, name):
    return _iric.cg_iRIC_Read_BC_FunctionalSize(fid, type, num, name)

def cg_iRIC_Read_BC_FunctionalWithName_String(fid, type, num, name, paramname):
    return _iric.cg_iRIC_Read_BC_FunctionalWithName_String(fid, type, num, name, paramname)

def cg_iRIC_Clear_BC(fid):
    return _iric.cg_iRIC_Clear_BC(fid)

def cg_iRIC_Write_BC_Integer(fid, type, num, name, value):
    return _iric.cg_iRIC_Write_BC_Integer(fid, type, num, name, value)

def cg_iRIC_Write_BC_Real(fid, type, num, name, value):
    return _iric.cg_iRIC_Write_BC_Real(fid, type, num, name, value)

def cg_iRIC_Write_BC_String(fid, type, num, name, value):
    return _iric.cg_iRIC_Write_BC_String(fid, type, num, name, value)

def cg_iRIC_Write_BC_FunctionalWithName_String(fid, type, num, name, paramname, value):
    return _iric.cg_iRIC_Write_BC_FunctionalWithName_String(fid, type, num, name, paramname, value)

def cg_iRIC_Read_Grid2d_Str_Size(fid):
    return _iric.cg_iRIC_Read_Grid2d_Str_Size(fid)

def cg_iRIC_Read_Grid3d_Str_Size(fid):
    return _iric.cg_iRIC_Read_Grid3d_Str_Size(fid)

def cg_iRIC_Read_Grid_TriangleElementsSize(fid):
    return _iric.cg_iRIC_Read_Grid_TriangleElementsSize(fid)

def cg_iRIC_Read_Grid_TriangleElementsSize2(fid):
    return _iric.cg_iRIC_Read_Grid_TriangleElementsSize2(fid)

def cg_iRIC_Read_Grid_NodeCount(fid):
    return _iric.cg_iRIC_Read_Grid_NodeCount(fid)

def cg_iRIC_Read_Grid_CellCount(fid):
    return _iric.cg_iRIC_Read_Grid_CellCount(fid)

def cg_iRIC_Read_Grid_IFaceCount(fid):
    return _iric.cg_iRIC_Read_Grid_IFaceCount(fid)

def cg_iRIC_Read_Grid_JFaceCount(fid):
    return _iric.cg_iRIC_Read_Grid_JFaceCount(fid)

def cg_iRIC_Read_Grid_KFaceCount(fid):
    return _iric.cg_iRIC_Read_Grid_KFaceCount(fid)

def cg_iRIC_Read_Grid_FunctionalDimensionSize(fid, name, dimname):
    return _iric.cg_iRIC_Read_Grid_FunctionalDimensionSize(fid, name, dimname)

def cg_iRIC_Read_Grid_FunctionalTimeSize(fid, name):
    return _iric.cg_iRIC_Read_Grid_FunctionalTimeSize(fid, name)

def cg_iRIC_Read_Grid2d_Open(fid):
    return _iric.cg_iRIC_Read_Grid2d_Open(fid)

def cg_iRIC_Read_Sol_Grid2d_Open(fid, solid):
    return _iric.cg_iRIC_Read_Sol_Grid2d_Open(fid, solid)

def cg_iRIC_Read_Sol_Particle_Count(fid, step):
    return _iric.cg_iRIC_Read_Sol_Particle_Count(fid, step)

def cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname)

def cg_iRIC_Write_Sol_ParticleGroup_GroupBegin(fid, name):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupBegin(fid, name)

def cg_iRIC_Write_Sol_ParticleGroup_GroupEnd(fid):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupEnd(fid)

def cg_iRIC_Write_Sol_ParticleGroup_Pos2d(fid, x, y):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos2d(fid, x, y)

def cg_iRIC_Write_Sol_ParticleGroup_Pos3d(fid, x, y, z):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos3d(fid, x, y, z)

def cg_iRIC_Write_Sol_ParticleGroup_Integer(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Integer(fid, name, value)

def cg_iRIC_Write_Sol_ParticleGroup_Real(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Real(fid, name, value)

def cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname):
    return _iric.cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname)

def cg_iRIC_Read_Sol_PolyData_CoordinateCount(fid, step, groupname):
    return _iric.cg_iRIC_Read_Sol_PolyData_CoordinateCount(fid, step, groupname)

def cg_iRIC_Write_Sol_PolyData_GroupBegin(fid, name):
    return _iric.cg_iRIC_Write_Sol_PolyData_GroupBegin(fid, name)

def cg_iRIC_Write_Sol_PolyData_GroupEnd(fid):
    return _iric.cg_iRIC_Write_Sol_PolyData_GroupEnd(fid)

def cg_iRIC_Write_Sol_PolyData_Integer(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_PolyData_Integer(fid, name, value)

def cg_iRIC_Write_Sol_PolyData_Real(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_PolyData_Real(fid, name, value)

def cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step):
    return _iric.cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step)

def cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname)

def cg_iRIC_Write_Sol_ParticleGroup_GroupBegin_WithGridId(fid, gid, name):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupBegin_WithGridId(fid, gid, name)

def cg_iRIC_Write_Sol_ParticleGroup_GroupEnd_WithGridId(fid, gid):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupEnd_WithGridId(fid, gid)

def cg_iRIC_Write_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, x, y):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, x, y)

def cg_iRIC_Write_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, x, y, z):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, x, y, z)

def cg_iRIC_Write_Sol_ParticleGroup_Integer_WithGridId(fid, gid, name, value):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Integer_WithGridId(fid, gid, name, value)

def cg_iRIC_Write_Sol_ParticleGroup_Real_WithGridId(fid, gid, name, value):
    return _iric.cg_iRIC_Write_Sol_ParticleGroup_Real_WithGridId(fid, gid, name, value)

def cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname):
    return _iric.cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname)

def cg_iRIC_Read_Sol_PolyData_CoordinateCount_WithGridId(fid, gid, step, groupname):
    return _iric.cg_iRIC_Read_Sol_PolyData_CoordinateCount_WithGridId(fid, gid, step, groupname)

def cg_iRIC_Write_Sol_PolyData_GroupBegin_WithGridId(fid, gid, name):
    return _iric.cg_iRIC_Write_Sol_PolyData_GroupBegin_WithGridId(fid, gid, name)

def cg_iRIC_Write_Sol_PolyData_GroupEnd_WithGridId(fid, gid):
    return _iric.cg_iRIC_Write_Sol_PolyData_GroupEnd_WithGridId(fid, gid)

def cg_iRIC_Write_Sol_PolyData_Integer_WithGridId(fid, gid, name, value):
    return _iric.cg_iRIC_Write_Sol_PolyData_Integer_WithGridId(fid, gid, name, value)

def cg_iRIC_Write_Sol_PolyData_Real_WithGridId(fid, gid, name, value):
    return _iric.cg_iRIC_Write_Sol_PolyData_Real_WithGridId(fid, gid, name, value)

def cg_iRIC_Read_Sol_Count(fid):
    return _iric.cg_iRIC_Read_Sol_Count(fid)

def cg_iRIC_Read_Sol_Time(fid, step):
    return _iric.cg_iRIC_Read_Sol_Time(fid, step)

def cg_iRIC_Read_Sol_Iteration(fid, step):
    return _iric.cg_iRIC_Read_Sol_Iteration(fid, step)

def cg_iRIC_Read_Sol_BaseIterative_Integer(fid, step, name):
    return _iric.cg_iRIC_Read_Sol_BaseIterative_Integer(fid, step, name)

def cg_iRIC_Read_Sol_BaseIterative_Real(fid, step, name):
    return _iric.cg_iRIC_Read_Sol_BaseIterative_Real(fid, step, name)

def cg_iRIC_Read_Sol_BaseIterative_String(fid, step, name):
    return _iric.cg_iRIC_Read_Sol_BaseIterative_String(fid, step, name)

def cg_iRIC_Write_Sol_Start(fid):
    return _iric.cg_iRIC_Write_Sol_Start(fid)

def cg_iRIC_Write_Sol_End(fid):
    return _iric.cg_iRIC_Write_Sol_End(fid)

def cg_iRIC_Write_Sol_Time(fid, time):
    return _iric.cg_iRIC_Write_Sol_Time(fid, time)

def cg_iRIC_Write_Sol_Iteration(fid, index):
    return _iric.cg_iRIC_Write_Sol_Iteration(fid, index)

def cg_iRIC_Write_Sol_BaseIterative_Integer(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_BaseIterative_Integer(fid, name, value)

def cg_iRIC_Write_Sol_BaseIterative_Real(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_BaseIterative_Real(fid, name, value)

def cg_iRIC_Write_Sol_BaseIterative_String(fid, name, value):
    return _iric.cg_iRIC_Write_Sol_BaseIterative_String(fid, name, value)

def cg_iRIC_Write_ErrorCode(fid, errorcode):
    return _iric.cg_iRIC_Write_ErrorCode(fid, errorcode)

def cg_iRIC_Read_BC_Indices_WithGridId(fid, gid, type, num, idx_arr):
    return _iric.cg_iRIC_Read_BC_Indices_WithGridId(fid, gid, type, num, idx_arr)

def cg_iRIC_Read_BC_Functional_WithGridId(fid, gid, type, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Read_BC_Functional_WithGridId(fid, gid, type, num, name, x_arr, y_arr)

def cg_iRIC_Read_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Read_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v_arr)

def cg_iRIC_Write_BC_Indices_WithGridId(fid, gid, type, num, idx_arr):
    return _iric.cg_iRIC_Write_BC_Indices_WithGridId(fid, gid, type, num, idx_arr)

def cg_iRIC_Write_BC_Indices2_WithGridId(fid, gid, type, num, idx_arr):
    return _iric.cg_iRIC_Write_BC_Indices2_WithGridId(fid, gid, type, num, idx_arr)

def cg_iRIC_Write_BC_Functional_WithGridId(fid, gid, type, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Write_BC_Functional_WithGridId(fid, gid, type, num, name, x_arr, y_arr)

def cg_iRIC_Write_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Write_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v_arr)

def cg_iRIC_Read_Functional(fid, name, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Functional(fid, name, x_arr, y_arr)

def cg_iRIC_Read_FunctionalWithName(fid, name, paramname, v_arr):
    return _iric.cg_iRIC_Read_FunctionalWithName(fid, name, paramname, v_arr)

def cg_iRIC_Write_Functional(fid, name, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Functional(fid, name, x_arr, y_arr)

def cg_iRIC_Write_FunctionalWithName(fid, name, paramname, v_arr):
    return _iric.cg_iRIC_Write_FunctionalWithName(fid, name, paramname, v_arr)

def cg_iRIC_Read_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x_arr, y_arr)

def cg_iRIC_Read_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Read_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v_arr)

def cg_iRIC_Read_Grid_Complex_Node_WithGridId(fid, gid, groupname, v_arr):
    return _iric.cg_iRIC_Read_Grid_Complex_Node_WithGridId(fid, gid, groupname, v_arr)

def cg_iRIC_Read_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v_arr):
    return _iric.cg_iRIC_Read_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v_arr)

def cg_iRIC_Write_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x_arr, y_arr)

def cg_iRIC_Write_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Write_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v_arr)

def cg_iRIC_Write_Grid_Complex_Node_WithGridId(fid, gid, groupname, v_arr):
    return _iric.cg_iRIC_Write_Grid_Complex_Node_WithGridId(fid, gid, groupname, v_arr)

def cg_iRIC_Write_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v_arr):
    return _iric.cg_iRIC_Write_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v_arr)

def iRIC_Geo_Polygon_Read_Points(id, x_arr, y_arr):
    return _iric.iRIC_Geo_Polygon_Read_Points(id, x_arr, y_arr)

def iRIC_Geo_Polygon_Read_HolePoints(id, holeid, x_arr, y_arr):
    return _iric.iRIC_Geo_Polygon_Read_HolePoints(id, holeid, x_arr, y_arr)

def iRIC_Geo_RiverSurvey_Read_Altitudes(id, pointid, position_arr, height_arr, active_arr):
    return _iric.iRIC_Geo_RiverSurvey_Read_Altitudes(id, pointid, position_arr, height_arr, active_arr)

def cg_iRIC_Read_Grid2d_Coords_WithGridId(fid, gid, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Grid2d_Coords_WithGridId(fid, gid, x_arr, y_arr)

def cg_iRIC_Read_Grid3d_Coords_WithGridId(fid, gid, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Grid3d_Coords_WithGridId(fid, gid, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Grid_TriangleElements_WithGridId(fid, gid, id_arr):
    return _iric.cg_iRIC_Read_Grid_TriangleElements_WithGridId(fid, gid, id_arr)

def cg_iRIC_Read_Grid_Real_Node_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Real_Node_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Grid_Integer_Node_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Integer_Node_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Grid_Real_Cell_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Real_Cell_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Grid_Integer_Cell_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Integer_Cell_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Grid_FunctionalDimension_Integer_WithGridId(fid, gid, name, dimname, v_arr):
    return _iric.cg_iRIC_Read_Grid_FunctionalDimension_Integer_WithGridId(fid, gid, name, dimname, v_arr)

def cg_iRIC_Read_Grid_FunctionalDimension_Real_WithGridId(fid, gid, name, dimname, v_arr):
    return _iric.cg_iRIC_Read_Grid_FunctionalDimension_Real_WithGridId(fid, gid, name, dimname, v_arr)

def cg_iRIC_Read_Grid_FunctionalTime_WithGridId(fid, gid, name, time_arr):
    return _iric.cg_iRIC_Read_Grid_FunctionalTime_WithGridId(fid, gid, name, time_arr)

def cg_iRIC_Read_Grid_Functional_Integer_Node_WithGridId(fid, gid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Integer_Node_WithGridId(fid, gid, name, dimid, v_arr)

def cg_iRIC_Read_Grid_Functional_Real_Node_WithGridId(fid, gid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Real_Node_WithGridId(fid, gid, name, dimid, v_arr)

def cg_iRIC_Read_Grid_Functional_Integer_Cell_WithGridId(fid, gid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Integer_Cell_WithGridId(fid, gid, name, dimid, v_arr)

def cg_iRIC_Read_Grid_Functional_Real_Cell_WithGridId(fid, gid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Real_Cell_WithGridId(fid, gid, name, dimid, v_arr)

def cg_iRIC_Write_Grid1d_Coords_WithGridId(fid, isize, x_arr):
    return _iric.cg_iRIC_Write_Grid1d_Coords_WithGridId(fid, isize, x_arr)

def cg_iRIC_Write_Grid2d_Coords_WithGridId(fid, isize, jsize, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Grid2d_Coords_WithGridId(fid, isize, jsize, x_arr, y_arr)

def cg_iRIC_Write_Grid3d_Coords_WithGridId(fid, isize, jsize, ksize, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Write_Grid3d_Coords_WithGridId(fid, isize, jsize, ksize, x_arr, y_arr, z_arr)

def cg_iRIC_Write_Grid_Real_Node_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Real_Node_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Grid_Integer_Node_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Integer_Node_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Grid_Real_Cell_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Real_Cell_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Grid_Integer_Cell_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Integer_Cell_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Grid2d_InterpolateWithCell(grid_handle, x, y, cellId, nodeids_arr, weights_arr):
    return _iric.cg_iRIC_Read_Grid2d_InterpolateWithCell(grid_handle, x, y, cellId, nodeids_arr, weights_arr)

def cg_iRIC_Read_Complex_Functional(fid, groupname, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Complex_Functional(fid, groupname, num, name, x_arr, y_arr)

def cg_iRIC_Read_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Read_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v_arr)

def cg_iRIC_Write_Complex_Functional(fid, groupname, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Complex_Functional(fid, groupname, num, name, x_arr, y_arr)

def cg_iRIC_Write_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Write_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v_arr)

def cg_iRIC_Read_BC_Indices(fid, type, num, idx_arr):
    return _iric.cg_iRIC_Read_BC_Indices(fid, type, num, idx_arr)

def cg_iRIC_Read_BC_Functional(fid, type, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Read_BC_Functional(fid, type, num, name, x_arr, y_arr)

def cg_iRIC_Read_BC_FunctionalWithName(fid, type, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Read_BC_FunctionalWithName(fid, type, num, name, paramname, v_arr)

def cg_iRIC_Write_BC_Indices(fid, type, num, idx_arr):
    return _iric.cg_iRIC_Write_BC_Indices(fid, type, num, idx_arr)

def cg_iRIC_Write_BC_Indices2(fid, type, num, idx_arr):
    return _iric.cg_iRIC_Write_BC_Indices2(fid, type, num, idx_arr)

def cg_iRIC_Write_BC_Functional(fid, type, num, name, x_arr, y_arr):
    return _iric.cg_iRIC_Write_BC_Functional(fid, type, num, name, x_arr, y_arr)

def cg_iRIC_Write_BC_FunctionalWithName(fid, type, num, name, paramname, v_arr):
    return _iric.cg_iRIC_Write_BC_FunctionalWithName(fid, type, num, name, paramname, v_arr)

def cg_iRIC_Read_Grid_Complex_Node(fid, groupname, v_arr):
    return _iric.cg_iRIC_Read_Grid_Complex_Node(fid, groupname, v_arr)

def cg_iRIC_Read_Grid_Complex_Cell(fid, groupname, v_arr):
    return _iric.cg_iRIC_Read_Grid_Complex_Cell(fid, groupname, v_arr)

def cg_iRIC_Write_Grid_Complex_Node(fid, groupname, v_arr):
    return _iric.cg_iRIC_Write_Grid_Complex_Node(fid, groupname, v_arr)

def cg_iRIC_Write_Grid_Complex_Cell(fid, groupname, v_arr):
    return _iric.cg_iRIC_Write_Grid_Complex_Cell(fid, groupname, v_arr)

def cg_iRIC_Read_Grid2d_Coords(fid, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Grid2d_Coords(fid, x_arr, y_arr)

def cg_iRIC_Read_Grid3d_Coords(fid, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Grid3d_Coords(fid, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Grid_TriangleElements(fid, id_arr):
    return _iric.cg_iRIC_Read_Grid_TriangleElements(fid, id_arr)

def cg_iRIC_Read_Grid_Real_Node(fid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Real_Node(fid, name, v_arr)

def cg_iRIC_Read_Grid_Integer_Node(fid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Integer_Node(fid, name, v_arr)

def cg_iRIC_Read_Grid_Real_Cell(fid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Real_Cell(fid, name, v_arr)

def cg_iRIC_Read_Grid_Integer_Cell(fid, name, v_arr):
    return _iric.cg_iRIC_Read_Grid_Integer_Cell(fid, name, v_arr)

def cg_iRIC_Read_Grid_FunctionalDimension_Integer(fid, name, dimname, v_arr):
    return _iric.cg_iRIC_Read_Grid_FunctionalDimension_Integer(fid, name, dimname, v_arr)

def cg_iRIC_Read_Grid_FunctionalDimension_Real(fid, name, dimname, v_arr):
    return _iric.cg_iRIC_Read_Grid_FunctionalDimension_Real(fid, name, dimname, v_arr)

def cg_iRIC_Read_Grid_FunctionalTime(fid, name, time_arr):
    return _iric.cg_iRIC_Read_Grid_FunctionalTime(fid, name, time_arr)

def cg_iRIC_Read_Grid_Functional_Integer_Node(fid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Integer_Node(fid, name, dimid, v_arr)

def cg_iRIC_Read_Grid_Functional_Real_Node(fid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Real_Node(fid, name, dimid, v_arr)

def cg_iRIC_Read_Grid_Functional_Integer_Cell(fid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Integer_Cell(fid, name, dimid, v_arr)

def cg_iRIC_Read_Grid_Functional_Real_Cell(fid, name, dimid, v_arr):
    return _iric.cg_iRIC_Read_Grid_Functional_Real_Cell(fid, name, dimid, v_arr)

def cg_iRIC_Write_Grid1d_Coords(fid, isize, x_arr):
    return _iric.cg_iRIC_Write_Grid1d_Coords(fid, isize, x_arr)

def cg_iRIC_Write_Grid2d_Coords(fid, isize, jsize, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Grid2d_Coords(fid, isize, jsize, x_arr, y_arr)

def cg_iRIC_Write_Grid3d_Coords(fid, isize, jsize, ksize, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Write_Grid3d_Coords(fid, isize, jsize, ksize, x_arr, y_arr, z_arr)

def cg_iRIC_Write_Grid_Real_Node(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Real_Node(fid, name, v_arr)

def cg_iRIC_Write_Grid_Integer_Node(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Integer_Node(fid, name, v_arr)

def cg_iRIC_Write_Grid_Real_Cell(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Real_Cell(fid, name, v_arr)

def cg_iRIC_Write_Grid_Integer_Cell(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Grid_Integer_Cell(fid, name, v_arr)

def cg_iRIC_Read_Sol_Cell_Integer(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Cell_Integer(fid, step, name, v_arr)

def cg_iRIC_Read_Sol_Cell_Real(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Cell_Real(fid, step, name, v_arr)

def cg_iRIC_Write_Sol_Cell_Integer(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Cell_Integer(fid, name, v_arr)

def cg_iRIC_Write_Sol_Cell_Real(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Cell_Real(fid, name, v_arr)

def cg_iRIC_Read_Sol_Grid2d_Coords(fid, step, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_Grid2d_Coords(fid, step, x_arr, y_arr)

def cg_iRIC_Read_Sol_Grid3d_Coords(fid, step, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Sol_Grid3d_Coords(fid, step, x_arr, y_arr, z_arr)

def cg_iRIC_Write_Sol_Grid2d_Coords(fid, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_Grid2d_Coords(fid, x_arr, y_arr)

def cg_iRIC_Write_Sol_Grid3d_Coords(fid, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Write_Sol_Grid3d_Coords(fid, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Sol_IFace_Integer(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_IFace_Integer(fid, step, name, v_arr)

def cg_iRIC_Read_Sol_IFace_Real(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_IFace_Real(fid, step, name, v_arr)

def cg_iRIC_Write_Sol_IFace_Integer(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_IFace_Integer(fid, name, v_arr)

def cg_iRIC_Write_Sol_IFace_Real(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_IFace_Real(fid, name, v_arr)

def cg_iRIC_Read_Sol_JFace_Integer(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_JFace_Integer(fid, step, name, v_arr)

def cg_iRIC_Read_Sol_JFace_Real(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_JFace_Real(fid, step, name, v_arr)

def cg_iRIC_Write_Sol_JFace_Integer(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_JFace_Integer(fid, name, v_arr)

def cg_iRIC_Write_Sol_JFace_Real(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_JFace_Real(fid, name, v_arr)

def cg_iRIC_Read_Sol_KFace_Integer(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_KFace_Integer(fid, step, name, v_arr)

def cg_iRIC_Read_Sol_KFace_Real(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_KFace_Real(fid, step, name, v_arr)

def cg_iRIC_Write_Sol_KFace_Integer(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_KFace_Integer(fid, name, v_arr)

def cg_iRIC_Write_Sol_KFace_Real(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_KFace_Real(fid, name, v_arr)

def cg_iRIC_Read_Sol_Node_Integer(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Node_Integer(fid, step, name, v_arr)

def cg_iRIC_Read_Sol_Node_Real(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Node_Real(fid, step, name, v_arr)

def cg_iRIC_Write_Sol_Node_Integer(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Node_Integer(fid, name, v_arr)

def cg_iRIC_Write_Sol_Node_Real(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Node_Real(fid, name, v_arr)

def cg_iRIC_Read_Sol_Particle_Pos2d(fid, step, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Pos2d(fid, step, x_arr, y_arr)

def cg_iRIC_Read_Sol_Particle_Pos3d(fid, step, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Pos3d(fid, step, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Sol_Particle_Real(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Real(fid, step, name, v_arr)

def cg_iRIC_Read_Sol_Particle_Integer(fid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Integer(fid, step, name, v_arr)

def cg_iRIC_Write_Sol_Particle_Pos2d(fid, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Pos2d(fid, x_arr, y_arr)

def cg_iRIC_Write_Sol_Particle_Pos3d(fid, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Pos3d(fid, x_arr, y_arr, z_arr)

def cg_iRIC_Write_Sol_Particle_Real(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Real(fid, name, v_arr)

def cg_iRIC_Write_Sol_Particle_Integer(fid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Integer(fid, name, v_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Pos2d(fid, step, groupname, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos2d(fid, step, groupname, x_arr, y_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Pos3d(fid, step, groupname, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos3d(fid, step, groupname, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Real(fid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Real(fid, step, groupname, name, v_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Integer(fid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Integer(fid, step, groupname, name, v_arr)

def cg_iRIC_Read_Sol_PolyData_Pos2d(fid, step, groupname, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Pos2d(fid, step, groupname, x_arr, y_arr)

def cg_iRIC_Read_Sol_PolyData_Type(fid, step, groupname, v_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Type(fid, step, groupname, v_arr)

def cg_iRIC_Read_Sol_PolyData_Real(fid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Real(fid, step, groupname, name, v_arr)

def cg_iRIC_Read_Sol_PolyData_Integer(fid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Integer(fid, step, groupname, name, v_arr)

def cg_iRIC_Write_Sol_PolyData_Polygon(fid, numPoints, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_PolyData_Polygon(fid, numPoints, x_arr, y_arr)

def cg_iRIC_Write_Sol_PolyData_Polyline(fid, numPoints, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_PolyData_Polyline(fid, numPoints, x_arr, y_arr)

def cg_iRIC_Read_Sol_Cell_Integer_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Cell_Integer_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Read_Sol_Cell_Real_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Cell_Real_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Write_Sol_Cell_Integer_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Cell_Integer_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Sol_Cell_Real_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Cell_Real_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Sol_Grid2d_Coords_WithGridId(fid, gid, step, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_Grid2d_Coords_WithGridId(fid, gid, step, x_arr, y_arr)

def cg_iRIC_Read_Sol_Grid3d_Coords_WithGridId(fid, gid, step, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Sol_Grid3d_Coords_WithGridId(fid, gid, step, x_arr, y_arr, z_arr)

def cg_iRIC_Write_Sol_Grid2d_Coords_WithGridId(fid, gid, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_Grid2d_Coords_WithGridId(fid, gid, x_arr, y_arr)

def cg_iRIC_Write_Sol_Grid3d_Coords_WithGridId(fid, gid, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Write_Sol_Grid3d_Coords_WithGridId(fid, gid, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Sol_IFace_Integer_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_IFace_Integer_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Read_Sol_IFace_Real_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_IFace_Real_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Write_Sol_IFace_Integer_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_IFace_Integer_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Sol_IFace_Real_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_IFace_Real_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Sol_JFace_Integer_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_JFace_Integer_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Read_Sol_JFace_Real_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_JFace_Real_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Write_Sol_JFace_Integer_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_JFace_Integer_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Sol_JFace_Real_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_JFace_Real_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Sol_KFace_Integer_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_KFace_Integer_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Read_Sol_KFace_Real_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_KFace_Real_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Write_Sol_KFace_Integer_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_KFace_Integer_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Sol_KFace_Real_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_KFace_Real_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Sol_Node_Integer_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Node_Integer_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Read_Sol_Node_Real_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Node_Real_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Write_Sol_Node_Integer_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Node_Integer_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Sol_Node_Real_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Node_Real_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Sol_Particle_Pos2d_WithGridId(fid, gid, step, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Pos2d_WithGridId(fid, gid, step, x_arr, y_arr)

def cg_iRIC_Read_Sol_Particle_Pos3d_WithGridId(fid, gid, step, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Pos3d_WithGridId(fid, gid, step, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Sol_Particle_Real_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Real_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Read_Sol_Particle_Integer_WithGridId(fid, gid, step, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_Particle_Integer_WithGridId(fid, gid, step, name, v_arr)

def cg_iRIC_Write_Sol_Particle_Pos2d_WithGridId(fid, gid, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Pos2d_WithGridId(fid, gid, x_arr, y_arr)

def cg_iRIC_Write_Sol_Particle_Pos3d_WithGridId(fid, gid, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Pos3d_WithGridId(fid, gid, x_arr, y_arr, z_arr)

def cg_iRIC_Write_Sol_Particle_Real_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Real_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Write_Sol_Particle_Integer_WithGridId(fid, gid, name, v_arr):
    return _iric.cg_iRIC_Write_Sol_Particle_Integer_WithGridId(fid, gid, name, v_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, step, groupname, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, step, groupname, x_arr, y_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, step, groupname, x_arr, y_arr, z_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, step, groupname, x_arr, y_arr, z_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Real_WithGridId(fid, gid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Real_WithGridId(fid, gid, step, groupname, name, v_arr)

def cg_iRIC_Read_Sol_ParticleGroup_Integer_WithGridId(fid, gid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_ParticleGroup_Integer_WithGridId(fid, gid, step, groupname, name, v_arr)

def cg_iRIC_Read_Sol_PolyData_Pos2d_WithGridId(fid, gid, step, groupname, x_arr, y_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Pos2d_WithGridId(fid, gid, step, groupname, x_arr, y_arr)

def cg_iRIC_Read_Sol_PolyData_Type_WithGridId(fid, gid, step, groupname, v_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Type_WithGridId(fid, gid, step, groupname, v_arr)

def cg_iRIC_Read_Sol_PolyData_Real_WithGridId(fid, gid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Real_WithGridId(fid, gid, step, groupname, name, v_arr)

def cg_iRIC_Read_Sol_PolyData_Integer_WithGridId(fid, gid, step, groupname, name, v_arr):
    return _iric.cg_iRIC_Read_Sol_PolyData_Integer_WithGridId(fid, gid, step, groupname, name, v_arr)

def cg_iRIC_Write_Sol_PolyData_Polygon_WithGridId(fid, gid, numPoints, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_PolyData_Polygon_WithGridId(fid, gid, numPoints, x_arr, y_arr)

def cg_iRIC_Write_Sol_PolyData_Polyline_WithGridId(fid, gid, numPoints, x_arr, y_arr):
    return _iric.cg_iRIC_Write_Sol_PolyData_Polyline_WithGridId(fid, gid, numPoints, x_arr, y_arr)


